ISISNeutronMuon/MDANSE

- Extensions/xtc/src/xdr_seek.c
Fixes #31 and closes #32
The seek function uses during the calculation of offsets and the length used `_MSVC_VER` predefined macro to recognise the system as Windows and therefore use the appropriate function, `_fseeki64`, for the seeking process. However, such a macro does not exist, resulting in seeking occurring using the `fseek` function instead, which causes errors with large trajectories. This has been fixed by correcting the name of the predefined macro to `_MSC_VER` which does exist and so makes the code run as intended.
**To test:**
1. Acquire a large Gromacs trajectory (at least 75000 frames). Contact me or @sanghamitra-mukhopadhyay if you do not have one.
2. Run Gromacs converter on the trajectory using MDANSE from this branch
---
Please comment on the …
> Fix Gromacs converter via macro name correction

- Src/Framework/Jobs/Castep.py
Fixes #38, making progress on #27 
Currently, CASTEP converter correctly reads velocities and forces from MD files, but it does not save them into NetCDF file correctly. The cause of this has been identified as the fact that forces are saved as [energy] gradients, though the exact reason why MMTK has issues with gradients is unknown. By saving forces as forces, the same way it is done in the DL_POLY converter which works well, the CASTEP converter now correctly saves the read velocities into the .nc file, which then can be used in analyses.
**To test:**
1. Convert an MD file using the CASTEP converter.
2. Use that converted NetCDF file for the Current Correlation Function (or other ones which require velocities) analysis.
---
Please comment on the following ([full …
> Fix velocity reading in CASTEP converter

- Src/Framework/Jobs/GeneralAutoCorrelationFunction.py
- Src/Framework/Jobs/PositionAutoCorrelationFunction.py
Fixes #22 
Currently, normalisation does not work in GACF and PACF because during it, a part of the configuration dictionary which does not exist is being accessed. This has been fixed by add the necessary values to configuration. The old normalisation has also been replaced with the `MDANSE.Mathematics.Signal.normalize` function that is used in VACF.
**To test:**
1. Run GACF analysis with `normalize` box ticked.
2. Run PACF analysis with `normalize` box ticked.
---
- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in …
> Fix normalisation in GACF and PACF

- Src/GUI/Plugins/PlotterPlugin.py
In order to solve the issue #42. I added in case of standalone mode a splitter window which contains the dataset and data panel. A minimum size of 100 has been set for each of these panels in order to avoid then to collapse.
> 42 improve pane layout in plotter

- AUTHORS
- Extensions/xtc/src/xdr_seek.c
- Src/Framework/InputData/MMTKTrajectoryInputData.py
- Src/Framework/InputData/NetCDFInputData.py
- Src/Framework/Jobs/Castep.py
- Src/Framework/Jobs/DCDConverter.py
- Src/Framework/Jobs/DL_POLY.py
- Src/Framework/Jobs/Discover.py
- Src/Framework/Jobs/Forcite.py
- Src/Framework/Jobs/GeneralAutoCorrelationFunction.py
- Src/Framework/Jobs/Generic.py
- Src/Framework/Jobs/Gromacs.py
- Src/Framework/Jobs/LAMMPS.py
- Src/Framework/Jobs/PairDistributionFunction.py
- Src/Framework/Jobs/PositionAutoCorrelationFunction.py
- Src/Framework/Jobs/VASP.py
- Src/GUI/ElementsDatabaseEditor.py
- Src/GUI/Plugins/Plotter1D.py
- Src/GUI/Plugins/PlotterPlugin.py
- Src/GUI/Plugins/PlotterSettings.py
Fixes #24 
Currently, it is possible to plot all variables in a NetCDF file, including those that have no use or even those that do not make sense, such as the description of the trajectory, or time against atomic mass. Several such variables have been prevented from being displayed in the list of variables. If anyone knows of other variables which should not be available for plotting, please let me know.
Furthermore, when data containing non-numeric values is attempted to be plotted, it now results in an error with a meaningful message without actually plotting the data.
**To test:**
1. Load an .nc file containing a trajectory into 2D/3D Plotter.
2. Observe that there are no variables titled 'description', 'step', or 'time' available for plotting.
---
Please …
> Remove ability to plot non-meaningful data

- .github/workflows/CI.yml
- BuildServer/Unix/tests.sh
- Src/Framework/Configurable.py
- Src/Framework/Configurators/NetCDFInputFileConfigurator.py
- Src/Framework/Formats/ASCIIFormat.py
- Src/Framework/Formats/NetCDFFormat.py
- Src/Framework/Formats/SVGFormat.py
- Src/Framework/InputData/NetCDFInputData.py
- Src/Framework/Jobs/LAMMPS.py
- Src/Framework/Jobs/McStasVirtualInstrument.py
- Src/Framework/Jobs/RigidBodyTrajectory.py
- Src/Framework/Jobs/StructureFactorFromScatteringFunction.py
- Src/Framework/OutputVariables/IOutputVariable.py
- Src/GUI/Plugins/DensitySuperpositionPlugin.py
- Src/GUI/Plugins/PlotterPlugin.py
- Src/GUI/Widgets/NetCDFInputFileWidget.py
- Tests/FunctionalTests/Jobs/BuildJobTests.py
- Tests/FunctionalTests/Jobs/test_gromacs_trr.py
In the process of getting rid of ScientificPython and MMTK, I use in this PR a dependency to NetCDF4 library which is standard (can you please install it in the build machine). I had to change the unit test and now some are breaking again. Could you please investigate on this Rastislav as you were on that topic a few days ago ? Many thanks in advances.
> Use netCDF4 as the NetCDF dependency instead of Scientific.IO/NetCDF

- .github/workflows/CI.yml
The continuous deployment part of the Ubuntu CI/CD pipeline is currently failing because `apt-get` is having issues. This can be solved by updating `apt-get` before it is used to install packages, as has been done for the CI part in #20 but forgotten for the CD part. This PR remedies that.
> Fix continuous deployment on Ubuntu

- .github/workflows/CI.yml
- Src/Framework/Jobs/CoordinationNumber.py
Fixes #87 
For some reason, the script `BuildServer/Unix/tests.sh`, when run on the MacOS pipeline, did not exit properly when tests were failing, making it appear as if the MacOS pipeline succeeded even though the tests failed. This has been resolved by not running the script and instead adding the commands to run test scripts directly to the CI.yml. Now, all pipelines fail correctly, as can be seen in this [run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2330594583).
---
- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small …
> Make MacOS CI fail when tests fail

- .github/workflows/CI.yml
Fixes #89 
Due to incorrect syntax in the MacOS CI part of the CI.yml, the netCDF4 python package was copied incorrectly, such that the insides of the netCDF4 folder were copied directly to site-packages. This has been fixed by correcting the copy syntax, so that the netCDF4 folder is created, and thus the package can be imported.
---
- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)? …
> Fix the installation of netCDF4 on MacOS CI/CD

- .github/workflows/CI.yml
Fixes #91 
MacOS CI was uploading artifacts even when the CD was not run, which shouldn't happen. This has been fixed by correcting the yaml syntax of the if statement such that now the artifacts are uploaded only when CD is run, just as it works in Ubuntu pipeline.
> Correct MacOS CI artifact upload mechanism

- Src/Framework/Units.yml
While updating the user guide, I noticed that the lumen and lux units didn't have steradian in their definition, so I have remedied that. Now `1 lm = 1 cd sr` and `1 lux = 1 cd sr m^-2`.
> Fix unit definitions

- Src/GUI/Plugins/AtomsListPlugin.py
- Src/GUI/Widgets/AtomsListWidget.py
*There is no associated issue.*
Currently, when `AtomsListPlugin` is opened through a 'New definition' button in 'Axis selection' or 'Reference basis' section, the nAtoms value, which controls the number of atoms that must be selected for the definition to be valid for use in the analysis from which the plugin was opened, is always set to 1. The reason for this was that the method handling the opening of this plugin in `AtomsListWidget` had a name that did not overwrite the name in the base class (`UserDefinitionWidget`), and therefore wasn't called anywhere to the best of my knowledge. By changing the name, the `AtomsListPlugin` is now created with `nAtoms` set to the value that is expected by the analysis.
However, further change was made to disable the input …
> Fix AtomsListPlugin

- Src/GUI/Widgets/AtomsListWidget.py
Fixes #21 
Until now, after an analysis that implements `AtomsListWidget` was opened, whenever any other analysis was attempted to be opened, a `ListenerMismatchError` would be returned, meaning that MDANSE had to be restarted to restore its functionality. This has been fixed by changing the arguments of the `AtomsListWidget.msg_set_ud()` method from `(self, message=None)` to `(self, message)`, which is the way that the method is implemented in the base class of `AtomsListWidget`, `UserDefinitionWidget`, and all of the base class's subclasses.
**To test:**
1. Open Angular correlation analysis
2. Open any other analysis
3. Observe that no error occurred
---
Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.h …
> Fix ListenerMismatchError

- Src/Framework/Jobs/Eccentricity.py
Fixes #98 
When atom selection was used in the Eccentricity analysis, it would fail. However, the bigger issue is that the `centre_of_masses()` function is currently called using the positions and masses from the atom selection rather than the centre of masses selection. Thanks @eurydice76 for fixing this in protos and thus showing the solution for this! By using the coordinates and masses associated with the centre of masses selection, both issues should be fixed.
**To test:**
1. Run the Eccentricity analysis with various combinations of Atom selections and Centre of masses selections.
2. Observe no errors
---
- Is the code of an acceptable …
> Fix centre of masses calculation in Eccentricity

- BuildServer/Unix/MacOS/deploy.sh
MacOS CD was failing due to changes in #94. There was an issue with uninstalling sphinx after building documentation has been, which has been fixed here, so the entire pipeline now works correctly.
> Fix MacOS CD

- Src/GUI/MainFrame.py
Fixes #48 
On Windows, the 'Toggle toolbar' button was hiding the wrong thing. This was likely caused by the removal of the `ToolBar` from the `MainFrame`. It has been fixed by using the `toggle_window()` method which is used by the other Toggle options, and then calling `self.Layout()`.
**To test:**
1. In the View menu, click on the 'Toggle toolbar' button and observe that the toolbar is hidden correctly
2. Click the same button again, and observe that everything is as it was before the button was clicked the first time.
@eurydice76, can you please check that everything still works correctly on Ubuntu? Thanks!
---
- Is the code of an acceptable …
> Fix Toggle toolbar option

- .github/workflows/CI.yml
When #35 was merged, the new dependency, [psutil](https://pypi.org/project/psutil/), was forgotten to be added to CI.yml so that it is installed during the CI/CD. Therefore, in the created installers the 'automatic' interpolation mode in CCF is broken. This has been fixed here.
> Install missing dependency in CI/CD

- .github/workflows/CI.yml
Fixes #105 
MDANSE installed from the CD-generated installers could not be started on Ubuntu. This was caused by the way `setuptools.setup` installs scripts, essentially the same issue as in #82. Switching to `distutils` fixed the issue.
The new installers can be found in [this run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2493806291).
> Fix ubuntu installers

- Src/Framework/InputData/NetCDFInputData.py
- Src/GUI/Plugins/PlotterData.py
- Src/GUI/Plugins/PlotterPlugin.py
- Src/IO/HDF5.py
- Src/IO/IOUtils.py
- Src/IO/NetCDF.py
- Src/IO/__init__.py
Fixes #113 
When abstraction was added to plotter in #86, a new column was added to the 'variable' part of the Data panel that shows the path of the variable in the file. However, this information is only available when the data is loaded via the `PlotterFrame` which uses the abstraction and the `netCDF4` or `h5py` package. In `MainFrame`, which loads in only MMTK NetCDF data and does so through the `MMTK` package, the path information does not exist.
Therefore, the `NetCDFInputData` class has been extended to also store path information. Further, the same recursive variable-searching pattern was applied to it as is used in the `NetCDFPlotterData` class. Lastly, refactoring was performed to make easier future work.
**To test:**
1. Open the result of analysis …
> Add path information to NetCDFInputData

- .github/workflows/CI.yml
- BuildServer/Windows/setup_ci.bat
#122 did not fix the Windows name due to issues  unique to the Windows script. The syntax in it has been corrected and gives correct values.
> Fix windows installer version

- CHANGELOG
- Src/Framework/Configurators/PythonObjectConfigurator.py
- Src/GUI/Widgets/PythonObjectWidgets.py
Fixes #126 
The error messages when incorrect Python syntax is inputted in the parts of MDANSE that use `PythonObjectConfigurator` are currently very unhelpful. This has been improved by catching the `SyntaxError` returned by `ast.parse` and adding additional information.
**To test**
1. Open e.g. DL_POLY converter
2. Type a syntactically incorrect input into the 'aliases' field (e.g. `{"}`)
3. Observe that the error is helpful
> Improve the parsing error messages

- .github/workflows/CI.yml
- CHANGELOG
Fixes #158 
The parts of MDANSE that use VTK were crashing on the installer-gotten MDANSE on Ubuntu 22. This was caused by libstdc++ shared objects that were included in the installer bundle. Removing them before packaging mdanse on the build server has fixed the issue.
**To test**
1. Install MDANSE on Ubuntu 22 using [this installer.](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3051401626)
2. Load a trajectory and open Molecule Viewer (observe no crashes)
3. Open and start Animation (observe no crashes)
4. Open 2D/3D Plotter and plot a plot using the Elevation, Iso-Surface, and Scalar-Field plotters. (observe no crashes)
> Fix VTK parts of MDANSE on Ubuntu 22

- .github/workflows/CI.yml
- CHANGELOG
Fixes #151 
Installing MDANSE on Ubuntu 22 using the installer caused some system issues like warnings showing up in bash or the inability to use some utilities like nano. This was caused by the inclusion of `libtinfo.so.6` library with the installer (generated by conda on the CI/CD). Removing this library prior to packaging MDANSE has removed the issue.
**To test**
1. Download Ubuntu 22 installer from [here](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3009421555) and install it.
2. Open a new shell and use various command line tools.
3. Observe no issues.
> Fix system issues caused by Ubuntu 22 installer

- .github/workflows/CI.yml
- BuildServer/Unix/MacOS/deploy.sh
- BuildServer/Windows/deploy.bat
- CHANGELOG
- Doc/conf_api.py
Fixes #152 
MDANSE API documentation has inbuilt inheritance diagrams but they were not being displayed properly because graphviz was not being installed on CI/CD. This has been fixed by installing graphviz.
**To test**
1. Download one of the installers from [this run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3015397798) and install MDANSE.
2. Open MDANSE and click on the API documentation button in toolbar.
3. Navigate to e.g. `MDANSE.Framework.Jobs.AngularCorrelation`
4. Observe that below the 'Inheritance' heading is displayed and inheritance diagram.
I have tested this on Windows computer and Ubuntu VM, but everyone feel free to go over it yourselves. @MBartkowiakSTFC can you please test on MacOS?
> Fix inheritance diagrams in installer-enclosed documentation

- .github/workflows/CI.yml
- CHANGELOG
- Src/GUI/Plugins/TrajectoryViewerPlugin.py
Resolves #165 
The Trajectory Viewer has been made available both with and without Molecular Viewer. This way, it can be accessed on systems where Molecular Viewer is broken while retaining the easy functionality it has had, i.e. to select atoms with Molecular Viewer for plotting in Trajectory Viewer.
**To test**
1. Open MDANSE GUI and load a trajectory
2. Go to Plugins>Miscellaneous _without_ opening the Molecular Viewer and open the Trajectory Viewer
3. Plot something and close Trajectory Viewer
4. Open Molecular Viewer
5. Open Trajectory Viewer and plot something
> Make Trajectory Viewer available without Molecular Viewer

- .github/workflows/CI.yml
- Src/GUI/Plugins/MolecularViewerPlugin.py
The MolecularViewerPlugin now checks what platform it is on. If it is on MacOS ("Darwin"), it sets the ancestor of the plugin to a different value.
> Disable MolecularViewer on MacOS

- Src/GUI/PluginsTreePanel.py
My last change to the MolecularViewer plugin was not sufficient to make MDANSE work with MolecularViewer disabled on MacOS. This change should fix the problem.
MDANSE on other platforms was not affected to start with.
> Add a check for REGISTRY keys in PluginsTreePanel

- Src/GUI/UnitsEditor.py
This is a simple fix to make sure that the GUI remains responsive after the Units Editor has been closed.
This should fix the problem described here:
https://github.com/ISISNeutronMuon/MDANSE/issues/182
> Add EndModal before closing the dialog

- Src/Framework/Formats/ASCIIFormat.py
- Src/Framework/Jobs/DensityOfStates.py
- Src/Framework/Jobs/DynamicIncoherentStructureFactor.py
- Src/Framework/Jobs/GaussianDynamicIncoherentStructureFactor.py
- Src/Framework/Jobs/StructureFactorFromScatteringFunction.py
@MBartkowiakSTFC @sanghamitra-mukhopadhyay @gonzalezma After our discussion, I could finally find a way to implement a better output when ASCII is selected as the output file format for the analysis. Now, for 1D variables, the output file contains two columns one for the Y axis and one for the X axis and for 2D variables the output contains the matrix with the X axis as the 1st column and the Y axis as the 1st row. While doing this, the support for data whose dimensionality is > 2 has been stopped because 1) so far there has never been such data produced by MDANSE 2) it makes nearly impossible the handling of the dependant axis when producing the output.  I also fixed some bugs in "time_window" output variable which was set as depending upon "time" variable which is not true.
> Improved the contents of the output file in case of ASCII selection

- .github/workflows/CI.yml
To address the issue:
https://github.com/ISISNeutronMuon/MDANSE/issues/196
I have changed the CI.yml file so that it does not include the workflow for Ubuntu 18.04 anymore.
> Remove Ubuntu 18.04 from the CI/CD workflow

- Src/MolecularDynamics/UnitCell.py
- Tests/UnitTests/TestUnitCell.py
Not much different in this one, I have just written tests and added type hints. The main thing is that I added a check for the passed in unit cell; if it is not 3×3, a `ValueError` is raised. I think this should make sense since this should be the only shape that a unit cell can ever be, but please correct me if I am wrong. Having the check here means that we do not have to constantly check for it in `Configuration` methods..
> Add tests for UnitCell

- Extensions/fast_calculation.pyx
- Src/MolecularDynamics/Analysis.py
- Src/MolecularDynamics/TrajectoryUtils.py
- Tests/UnitTests/TestAnalysis.py
- Tests/UnitTests/TestTrajectoryUtils.py
As in the other PRs, I have mostly just expanded documentation, added type hints, and written unit tests. The only code change is that in `cpt_cluster_connectivity_nopbc` no longer takes an empty list as an argument and instead creates an empty list itself. I can't remember exactly why I made that change, but I think it was causing a bug. However, I have one question:
1. In `build_connectivity()`, shouldn't we call the `cpt_cluster_connectivity_nopbc` function only if the configuration is `RealConfiguration`, and then use `cpt_cluster_connectivity_pbc` for when the configuration is `PeriodicBoxConfigutaion`? Further, shouldn't there be separate functions for `PeriodicBoxConfigutaion` and `PeriodicRealConfiguration`?
> Add tests for Analysis and TrajectoryUtils

- Extensions/atoms_in_shell.pyx
- Extensions/contiguous_coordinates.pyx
- Extensions/fold_coordinates.pyx
- Src/Framework/Selectors/WithinShell.py
- Src/Mathematics/Transformation.py
- Src/MolecularDynamics/Configuration.py
- Src/MolecularDynamics/UnitCell.py
- Tests/UnitTests/TestConfiguration.py
As with the other PRs, here I have also mostly just added type hints, expanded documentation. The tests now cover all classes and all methods;; I tried keeping the values from the previous tests where I was able to see which ones did what. In terms of documentation, I reformatted it to match the style from other parts of MDANSE, particularly the ones I have reviewed already. There were no major changes, only a couple minor ones:
1. I renamed the `atomsInShell()` method to `atoms_in_shell` so as to match both the names of the other methods and PEP8.
2. In the `contiguous_configuration` and `continuous_configuration` methods of `_PeriodicConfiguration` subclasses, I have changed the line `conf = self` to `conf = self.clone()` since I reckoned that the purpose of those methods was to return …
> Improve Configuration tests
